[package]
name = "latest-maven-version"
version = "0.3.0"
description = "Check maven central for the latest version of some artifact"
authors = ["Paul Horn <paul.horn@neotechnology.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
color-eyre = { version = "0.5.10", default-features = false }
console = { version = "0.13.0", default-features = false }
indicatif = { version = "0.15.0", optional = true }
itertools = "0.9.0"
lenient_semver = "0.3.0"
num_cpus = { version = "1.13.0", optional = true }
rpassword = "5.0.0"
semver = "0.11.0"
ureq = { version = "1.5.4", default-features = false, features = ["tls"] }
url = "2.2.0"
xmlparser = "0.13.3"

[features]
parallel = ["indicatif", "num_cpus"]

[dev-dependencies]
test-case = "1.0.0"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = true
opt-level = 2
rpath = false
