[package]
name = "latest-maven-version"
version = "0.1.0"
description = "Check maven central for the latest version of some artifact"
authors = ["Paul Horn <paul.horn@neotechnology.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = "3.0.0-beta.1"
color-eyre = "0.5.1"
eyre = "0.6.0"
itertools = "0.9.0"
semver = "0.10.0"
serde = { version = "1.0.115", features = ["derive"] }
serde-xml-rs = "0.4.0"
ureq = "1.3.0"
url = "2.1.1"
yansi = "0.5.0"
