[package]
name = "latest-maven-version"
version = "0.2.0"
description = "Check maven central for the latest version of some artifact"
authors = ["Paul Horn <paul.horn@neotechnology.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
color-eyre = "0.5.1"
# Keep 0.11.3 until dialoguer and indicatif have upgraded
console = { version = "0.11.3", default-features = false }
dialoguer = "0.6.2"
eyre = "0.6.0"
indicatif = "0.15.0"
itertools = "0.9.0"
num_cpus = "1.13.0"
semver = "0.10.0"
serde = { version = "1.0.115", features = ["derive"] }
serde-xml-rs = "0.4.0"
ureq = { version = "1.3.0", default-features = false, features = ["tls"] }
url = "2.1.1"
